/* The following code was generated by JFlex 1.4.1 on 2/17/11 8:56 PM */

package edu.pitt.math.jhol.core.parser;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 2/17/11 8:56 PM from the specification file
 * <tt>C:/Work/My Projects/Eclipse/jHOLLight/src/edu/pitt/math/jhol/core/lexer/Lexer.flex</tt>
 */
class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 1;
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  2,  0,  3,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3,  0,  9,  0,  0,  0,  0,  0, 10, 11,  0,  0, 14,  6,  0,  0, 
     8,  7,  7,  7,  7,  7,  7,  7,  7,  7, 16, 15,  0,  0,  0,  0, 
     0, 31,  4, 24,  4,  4,  4, 42, 36, 35,  4,  4, 38,  4,  4, 37, 
    41,  4,  4, 32, 17,  4, 23,  4,  4,  4,  4, 12,  0, 13,  0,  5, 
     0, 19, 30,  4,  4, 39,  4, 34, 40, 33,  4,  4, 43, 29, 26, 25, 
    20,  4, 22, 27, 28,  4, 21,  4,  4, 18,  4,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\12\3\1\15"+
    "\1\16\20\3\1\17\2\3\1\20\1\3\1\21\6\3"+
    "\1\22\2\3\1\23\2\3\1\24\1\25\1\26\1\27"+
    "\1\30\1\3\1\31\4\3\1\32\2\3\1\33\1\34"+
    "\2\3\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\130\0\260\0\334\0\u0108"+
    "\0\130\0\130\0\130\0\130\0\130\0\130\0\130\0\130"+
    "\0\u0134\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268"+
    "\0\u0294\0\u02c0\0\u02ec\0\130\0\u0318\0\u0344\0\u0370\0\u039c"+
    "\0\u03c8\0\u03f4\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\u04fc"+
    "\0\u0528\0\u0554\0\u0580\0\u05ac\0\260\0\u05d8\0\u0604\0\260"+
    "\0\u0630\0\260\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738"+
    "\0\260\0\u0764\0\u0790\0\260\0\u07bc\0\u07e8\0\260\0\260"+
    "\0\u0814\0\260\0\260\0\u0840\0\260\0\u086c\0\u0898\0\u08c4"+
    "\0\u08f0\0\260\0\u091c\0\u0948\0\260\0\260\0\u0974\0\u09a0"+
    "\0\260";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\3\1\7\1\10\1\3"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\5\6\1\22\1\23\6\6\1\24\1\25\2\6"+
    "\1\26\1\27\1\6\1\30\2\6\1\31\1\32\1\6"+
    "\1\33\1\3\1\0\6\33\1\34\42\33\56\0\1\5"+
    "\55\0\2\6\1\0\2\6\10\0\33\6\7\0\1\10"+
    "\53\0\2\10\47\0\2\6\1\0\2\6\10\0\1\6"+
    "\1\35\24\6\1\36\1\37\3\6\4\0\2\6\1\0"+
    "\2\6\10\0\2\6\1\40\30\6\4\0\2\6\1\0"+
    "\2\6\10\0\10\6\1\41\22\6\4\0\2\6\1\0"+
    "\2\6\10\0\15\6\1\42\15\6\4\0\2\6\1\0"+
    "\2\6\10\0\13\6\1\43\17\6\4\0\2\6\1\0"+
    "\2\6\10\0\11\6\1\44\21\6\4\0\2\6\1\0"+
    "\2\6\10\0\24\6\1\45\6\6\4\0\2\6\1\0"+
    "\2\6\10\0\20\6\1\46\12\6\4\0\2\6\1\0"+
    "\2\6\10\0\2\6\1\47\30\6\4\0\2\6\1\0"+
    "\2\6\10\0\10\6\1\50\22\6\1\33\2\0\6\33"+
    "\1\0\42\33\4\0\2\6\1\0\2\6\10\0\2\6"+
    "\1\51\1\6\1\52\26\6\4\0\2\6\1\0\2\6"+
    "\10\0\5\6\1\53\25\6\4\0\2\6\1\0\2\6"+
    "\10\0\26\6\1\54\4\6\4\0\2\6\1\0\2\6"+
    "\10\0\5\6\1\55\25\6\4\0\2\6\1\0\2\6"+
    "\10\0\11\6\1\56\2\6\1\57\16\6\4\0\2\6"+
    "\1\0\2\6\10\0\12\6\1\60\20\6\4\0\2\6"+
    "\1\0\2\6\10\0\5\6\1\61\25\6\4\0\2\6"+
    "\1\0\2\6\10\0\13\6\1\62\17\6\4\0\2\6"+
    "\1\0\2\6\10\0\25\6\1\63\5\6\4\0\2\6"+
    "\1\0\2\6\10\0\12\6\1\64\20\6\4\0\2\6"+
    "\1\0\2\6\10\0\20\6\1\65\12\6\4\0\2\6"+
    "\1\0\2\6\10\0\2\6\1\66\30\6\4\0\2\6"+
    "\1\0\2\6\10\0\3\6\1\67\27\6\4\0\2\6"+
    "\1\0\2\6\10\0\2\6\1\70\30\6\4\0\2\6"+
    "\1\0\2\6\10\0\14\6\1\71\16\6\4\0\2\6"+
    "\1\0\2\6\10\0\10\6\1\72\22\6\4\0\2\6"+
    "\1\0\2\6\10\0\12\6\1\73\20\6\4\0\2\6"+
    "\1\0\2\6\10\0\15\6\1\74\15\6\4\0\2\6"+
    "\1\0\2\6\10\0\20\6\1\75\12\6\4\0\2\6"+
    "\1\0\2\6\10\0\1\76\32\6\4\0\2\6\1\0"+
    "\2\6\10\0\13\6\1\77\17\6\4\0\2\6\1\0"+
    "\2\6\10\0\5\6\1\100\25\6\4\0\2\6\1\0"+
    "\2\6\10\0\32\6\1\101\4\0\2\6\1\0\2\6"+
    "\10\0\3\6\1\102\27\6\4\0\2\6\1\0\2\6"+
    "\10\0\5\6\1\103\25\6\4\0\2\6\1\0\2\6"+
    "\10\0\5\6\1\104\25\6\4\0\2\6\1\0\2\6"+
    "\10\0\13\6\1\105\17\6\4\0\2\6\1\0\2\6"+
    "\10\0\11\6\1\106\21\6\4\0\2\6\1\0\2\6"+
    "\10\0\1\6\1\107\31\6\4\0\2\6\1\0\2\6"+
    "\10\0\12\6\1\110\20\6\4\0\2\6\1\0\2\6"+
    "\10\0\26\6\1\111\4\6\4\0\2\6\1\0\2\6"+
    "\10\0\21\6\1\112\11\6\4\0\2\6\1\0\2\6"+
    "\10\0\3\6\1\113\27\6\4\0\2\6\1\0\2\6"+
    "\10\0\13\6\1\114\17\6\4\0\2\6\1\0\2\6"+
    "\10\0\14\6\1\115\16\6\4\0\2\6\1\0\2\6"+
    "\10\0\26\6\1\116\4\6\4\0\2\6\1\0\2\6"+
    "\10\0\2\6\1\117\30\6\4\0\2\6\1\0\2\6"+
    "\10\0\13\6\1\120\17\6\4\0\2\6\1\0\2\6"+
    "\10\0\26\6\1\121\4\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2508];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\3\1\10\11\13\1\1\11"+
    "\65\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
 //private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  //private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
        StringBuffer string = new StringBuffer();

        private Token lastToken;

        public Token peekToken() throws java.io.IOException {
                if (lastToken != null)
                        return lastToken;
                else
                        return lastToken = get_token();
        }

        public Token nextToken() throws java.io.IOException {
                if (lastToken != null) {
                        Token tmp = lastToken;
                        lastToken = null;
                        return tmp;
                }

                return get_token();
        }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    //zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yycolumn = 0;//yychar
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token get_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 11: 
          { return new Token(TokenType.SEMICOLON);
          }
        case 30: break;
        case 4: 
          { return new Token(TokenType.INTEGER, yytext());
          }
        case 31: break;
        case 14: 
          { yybegin(YYINITIAL); return new Token(TokenType.STRING, string.toString());
          }
        case 32: break;
        case 9: 
          { return new Token(TokenType.RBRACK);
          }
        case 33: break;
        case 24: 
          { return new Token(TokenType.Tyvar);
          }
        case 34: break;
        case 19: 
          { return new Token(TokenType.Comb);
          }
        case 35: break;
        case 1: 
          { System.err.println("Illegal character: "+yytext());
          }
        case 36: break;
        case 13: 
          { string.append( yytext() );
          }
        case 37: break;
        case 27: 
          { return new Token(TokenType.Theorem);
          }
        case 38: break;
        case 16: 
          { return new Token(TokenType.Abs);
          }
        case 39: break;
        case 23: 
          { return new Token(TokenType.Tyapp);
          }
        case 40: break;
        case 22: 
          { return new Token(TokenType.Goal);
          }
        case 41: break;
        case 21: 
          { return new Token(TokenType.Pair);
          }
        case 42: break;
        case 12: 
          { return new Token(TokenType.COLON);
          }
        case 43: break;
        case 29: 
          { return new Token(TokenType.Goalstate);
          }
        case 44: break;
        case 20: 
          { return new Token(TokenType.List);
          }
        case 45: break;
        case 15: 
          { return new Token(TokenType.Var);
          }
        case 46: break;
        case 3: 
          { return new Token(TokenType.IDENTIFIER, yytext());
          }
        case 47: break;
        case 17: 
          { return new Token(TokenType.Int);
          }
        case 48: break;
        case 26: 
          { return new Token(TokenType.String);
          }
        case 49: break;
        case 7: 
          { return new Token(TokenType.RPAR);
          }
        case 50: break;
        case 10: 
          { return new Token(TokenType.COMMA);
          }
        case 51: break;
        case 8: 
          { return new Token(TokenType.LBRACK);
          }
        case 52: break;
        case 28: 
          { return new Token(TokenType.HOLType);
          }
        case 53: break;
        case 6: 
          { return new Token(TokenType.LPAR);
          }
        case 54: break;
        case 5: 
          { yybegin(STRING); string.setLength(0);
          }
        case 55: break;
        case 25: 
          { return new Token(TokenType.Const);
          }
        case 56: break;
        case 18: 
          { return new Token(TokenType.Term);
          }
        case 57: break;
        case 2: 
          { 
          }
        case 58: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return new Token(TokenType.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
