# -*- Makefile -*-
# $Id: Makefile.config,v 1.11 2010/04/04 19:38:40 rjones Exp $

PACKAGE := weylbot
VERSION := 0.9

# Prefix for installation.
# - Binaries are installed in $(PREFIX)/sbin
# - Other files go in $(PREFIX)/share/$(PACKAGE)
PREFIX=/usr/local

BINDIR=$(PREFIX)/bin
SBINDIR=$(PREFIX)/sbin
DATADIR=$(PACKAGE)/share/$(PACKAGE)

# Install location of the SUID wrapper.
WRAPPER=$(SBINDIR)/hollightwrapper

# Location where the init script is installed.
INITSCRIPT=$(DATADIR)/init

# Location (directory) for chrooted environment.
CHROOTDIR=/home/hol

# Location of ocaml program.
#OCAML=/usr/bin/ocaml

# OCaml command user.
OCAMLUSER=nobody

#----------------------------------------------------------------------
# If you want to run the bot without installing, leave the
# following lines uncommented.
#
# You will also need to create directory $(CHROOTDIR),
# compile everything, and then 'sudo make permissions'
# which is just the same doing:
#
#   chown root.root ocamlbotwrapper
#   chmod ug+s ocamlbotwrapper
#
#INITSCRIPT=init
WRAPPER=/usr/local/bin/hol_light
