#!/bin/bash
export FLYSPECK_REV="`svnversion flyspeck`"
export FLYSPECK_DIR="`pwd`/flyspeck/text_formalization"
export HOLLIGHT_DIR="`pwd`/hol_light"
 
cr_run ocampl -I hol_light -I text_formalization -init auto-update.ml
