#!/bin/bash
FLYSPECK_SOURCE=`readlink --canonicalize --no-newline $BASH_SOURCE`
FLYSPECK_DIR=`dirname $FLYSPECK_SOURCE`
cd $FLYSPECK_DIR

export FLYSPECK_DIR

#requires:
# ocaml>=3.09
# blcr 
ocamlmktop unix.cma str.cma nums.cma -o ocampl
screen -d -m cr_run ./ocampl -I $HOLLIGHT_DIR -I $FLYSPECK_DIR -init boot.ml
