#!/bin/bash
JHOL_SOURCE=`readlink --canonicalize --no-newline $BASH_SOURCE`
JHOL_DIR=`dirname $JHOL_SOURCE`
cd $JHOL_DIR

export FLYSPECK_REV="`svnversion ../text_formalization`"
export FLYSPECK_DIR="../text_formalization"
 
screen -d cr_run ocampl -I $HOLLIGHT_DIR -I $FLYSPECK_DIR -init auto-update.ml
