#!/bin/bash
JHOL_DIR=`dirname $BASH_SOURCE`
export FLYSPECK_REV="`svnversion $JHOL_DIR/..`"
export FLYSPECK_DIR="$JHOL_DIR/../text_formalization"
export HOLLIGHT_DIR="`cat $JHOL_DIR/HOLLIGHT_DIR`"
 
cr_run ocampl -I $HOLLIGHT_DIR -I $FLYSPECK_DIR -init $JHOL_DIR/auto-update.ml
