#!/bin/bash
FLYSPECK_SOURCE=`readlink --canonicalize\
  --no-newline $BASH_SOURCE`
FLYSPECK_DIR=`dirname $FLYSPECK_SOURCE`
cd $FLYSPECK_DIR

rm -f release/lib/AppleJavaExtensions.jar
jsvc -cp release/lib/*:release/jHOLLib.jar\
  -home /home/hol\
  -user hol\
  edu.pitt.math.jhol.irc.HOLDaemon\
  `hostname -s` charizard.zapto.org 1
